import { Project } from './types';
export const myProjects: Project[] = [
  {
    title: 'Headless CMS',
    full_title: 'Ecommerce with Headless CMS',
    description:
      'Using Storyblok API to manage content and Next.js to render the pages. Images taken from fantastic clothing store Colourful Standard.',
    images: ['/ecom3.png', '/ecom2.png', '/ecom1.png'],
    link: 'https://ecommerce-headless-cms-storyblok-nextjs.vercel.app/',
    technologies: ['Next.js', 'Storyblok', 'Tailwind CSS'],
    deploy: 'Vercel',
    id: 1,
    short_description: 'With Storyblok and NEXT.js',
    preview_image: '/ecom-preview.png',
  },
  {
    title: 'Online Grocery Store',
    full_title: 'Ecommerce for Grocery Products',
    description:
      'Online store with a working database connected to the frontend. The site also includes a fully working custom made admin panel for working with products and orders.',
    images: ['/hakim1.png', '/hakim2.png', '/hakim3.png', '/hakim4.png'],
    link: 'https://hakims-livs-2304-g06x-client.vercel.app/',
    technologies: [
      'React/Vite',
      'Node.js',
      'Express',
      'MongoDB/Atlas',
      'Tailwind CSS/Shadcn UI',
    ],
    deploy: 'Vercel',
    id: 2,
    short_description: 'With Storyblok and NEXT.js',
    preview_image: '/hakim-preview.png',
  },
  {
    title: 'Chat App',
    full_title: 'Chat application',
    description:
      'A fullstack project and my first try at using Socket.IO to work with instant chat messaging. This project is still a work in progress and more updates are coming!',
    images: ['/chat1.png', '/chat2.png'],
    link: 'https://chattupp-client.onrender.com/',
    technologies: [
      'React/Vite',
      'Node.js',
      'Express',
      'MongoDB/Atlas',
      'Typescript',
      'React-Bootstrap',
    ],
    deploy: 'Render',
    id: 3,
    short_description: 'With Storyblok and Next.js',
    preview_image: '/chat1.png',
  },
  {
    title: 'User list',
    full_title: 'User list from API',
    description:
      'This is just a smaller frontend showcase from when I tried to work with Vue instead of React.',
    images: ['/vue1.png', '/vue2.png'],
    link: 'https://user-list-project.vercel.app/',
    technologies: ['Vue/Vite', 'Tailwind CSS'],
    deploy: 'Vercel',
    id: 4,
    short_description: 'Smaller project with Vue',
    preview_image: '/vue1.png',
  },
  // {
  //   title: 'Online Game Review Site',
  //   full_title: 'Online Game Review Platform',
  //   description: 'Work in progress: Fullstack web application for gaming enthusiasts to rate and view modern video games on all major gaming systems.',
  //   technologies: ['Next.js', 'Python', 'Python-Flask', 'SQLite', 'MaterialUI'],
  //   deploy: null,
  //   short_description: 'Fullstack web application for game reviews',
  // }
];
export const myProjectsSV: Project[] = [
  {
    title: 'Headless CMS',
    full_title: 'E-handel med Headless CMS',
    description:
      'Använder Storyblok API för att hantera innehåll och Next.js för att rendera sidorna. Bilder hämtade från den fantastiska klädbutiken Colourful Standard.',
    images: ['/ecom3.png', '/ecom2.png', '/ecom1.png'],
    link: 'https://ecommerce-headless-cms-storyblok-nextjs.vercel.app/',
    technologies: ['Next.js', 'Storyblok', 'Tailwind CSS'],
    deploy: 'Vercel',
    id: 1,
    short_description: 'Med Storyblok och NEXT.js',
    preview_image: '/ecom-preview.png',
  },
  {
    title: 'Online Livsmedelsbutik',
    full_title: 'E-handel för livsmedelsprodukter',
    description:
      'Nätbutik med en fungerande databas kopplad till frontend. Webbplatsen inkluderar även en fullt fungerande egenbyggd adminpanel för att hantera produkter och beställningar.',
    images: ['/hakim1.png', '/hakim2.png', '/hakim3.png', '/hakim4.png'],
    link: 'https://hakims-livs-2304-g06x-client.vercel.app/',
    technologies: [
      'React/Vite',
      'Node.js',
      'Express',
      'MongoDB/Atlas',
      'Tailwind CSS/Shadcn UI',
    ],
    deploy: 'Vercel',
    id: 2,
    short_description: 'Med Storyblok och NEXT.js',
    preview_image: '/hakim-preview.png',
  },
  {
    title: 'Chatt App',
    full_title: 'Chatt applikation',
    description:
      'Ett fullstack-projekt och mitt första försök att använda Socket.IO för att arbeta med direktmeddelanden. Detta projekt är fortfarande under utveckling och fler uppdateringar kommer!',
    images: ['/hakim1.png', '/hakim2.png', '/hakim3.png', '/hakim4.png'],
    link: 'https://chattupp-client.onrender.com/',
    technologies: [
      'React/Vite',
      'Node.js',
      'Express',
      'MongoDB/Atlas',
      'Typescript',
      'React-Bootstrap',
    ],
    deploy: 'Render',
    id: 3,
    short_description: 'Med Storyblok och Next.js',
    preview_image: '/ecom-preview.png',
  },
  {
    title: 'Användarlista',
    full_title: 'Användarlista från API',
    description:
      'Detta är bara ett mindre frontend-projekt från när jag testade att arbeta med Vue istället för Vite.',
    images: ['/vue1.png', '/vue2.png'],
    link: 'https://user-list-project.vercel.app/',
    technologies: ['Vue/Vite', 'Tailwind CSS'],
    deploy: 'Vercel',
    id: 4,
    short_description: 'Mindre projekt med Vue',
    preview_image: '/ecom-preview.png',
  },
  // {
  //   title: 'Online Spelrecensionssida',
  //   full_title: 'Plattform för Spelrecensioner Online',
  //   description: 'Pågående arbete: Fullstack webbapplikation för spelentusiaster att betygsätta och se moderna videospel på alla stora spelsystem.',
  //   technologies: ['Next.js', 'Python', 'Python-Flask', 'SQLite', 'MaterialUI'],
  //   deploy: null,
  //   short_description: 'Fullstack webbapplikation för spelrecensioner',
  // }
];
